### ISSUE TITLE
Out of Memory Error with NVIDIA NeMo Speaker Diarization Model on Long Audios

### ISSUE THREAD

**Issue by zhangjoe99** [zhangjoe99/nemo-public-repo#1]
# Issue Description
Message me on sphinx if interested
## Overview
When attempting to process audio files longer than 1 hour using the NVIDIA NeMo speaker diarization model, the code throws an "Out of Memory" error. This issue appears to be related to vram memory consumption during the processing of longer audio segments.

## Environment
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"

## Error
![image](https://github.com/zhangjoe99/nemo-public-repo/assets/52080136/33f46ba9-474e-48b9-9b39-93bf79c2d869)

## To Run
Project runs in a docker container. Ex.
```
docker-compose build
docker-compose up
```

Example 2 hour audio file is provided in Dockerfile: https://github.com/zhangjoe99/nemo-public-repo/blob/3a4042037617683d306b17e915fb9d0bada7d788/nemo-engine/Dockerfile#L32

## Bounty acceptance
1. PR with modified code / nemo parameters to successfully complete speaker diarization of long audio files (2 hour provided but shuold work with 3 hour or even 4 hour audios as well). "nemo_results.json" should contain data such as
```
[[140, 1320, 2], [1580, 6120, 2], [6460, 6760, 2], [7020, 7480, 2]]
```
Where each triple in the list is [start_time_ms, end_time_ms, speaker]
The formatting is already done in code upon nemo completion.

2. AWS EC2 specs should also be given so we can replicate results.

**Comment by Khaalid-oh** [comment]
Hi, I can help

**Comment by aliraza556** [comment]
Hi @zhangjoe99
The task is available?

**Comment by Khaalid-oh** [comment]
> Hi @zhangjoe99 The task is available?

Not really, I'm on it

**Comment by zhangjoe99** [comment]
Hey @aliraza556. @Khaalid-oh, as discussed in our pms, I've removed you from the task since it's been over a week. Let's give others a shot at it. Of course, if you end up cracking it, definitely let me know.

**Comment by Khaalid-oh** [comment]
> Hey @aliraza556. @Khaalid-oh, as discussed in our pms, I've removed you from the task since it's been over a week. Let's give others a shot at it. Of course, if you end up cracking it, definitely let me know.

Okay thanks, I'll get back to you as soon as possible

**Comment by hkarani** [comment]
Hello @zhangjoe99. I might have solution for this. Can I give it a shot?

**Comment by zhangjoe99** [comment]
Fixed with https://github.com/zhangjoe99/nemo-public-repo/pull/3
